---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
    #labels:
    #    app: guestbook
    #    name: back-end-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-guestbook
        #name: back-end-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
    #labels:
    #    app: guestbook
    #    name: back-end-deployment
spec:
   # replicas: 1
  selector:
    matchLabels:
      app: redis-guestbook
          #name: back-end-pod
  template:
    metadata:
      labels:
        app: redis-guestbook
                #name: back-end-pod
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379