apiVersion: v1
kind: Service
metadata:
    name: redis-master
    labels:
        app: guestbook
        name: back-end-service
spec:
    ports:
    - port: 6379
      targetPort: 6379
    selector:
        app: guestbook
        name: back-end-pod