apiVersion: v1
kind: Service
metadata:
    name: front-end-service
    labels:
        app: guestbook
        name: front-end-service
spec:
    #type: LoadBalancer
    type: NodePort
    ports:
    - port: 80
      targetPort: 3000
    selector:
        app: guestbook
        name: front-end-pod