---
apiVersion: v1 

kind: Service

metadata:
  name: myapp-service

spec:
  selector:
    app: guestbook-app
  type: Nodeport
  ports:
   - port: 80
     targetPort: 80 

---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    app: guestbook-app 

spec:

  selector:
    matchLabels:
      app: guestbook-app

  template:
    metadata: 
      name: myapp-pod
      labels:
        app: guestbook-app
    spec:
      containers:
        - name: my-guestbook-app
          image: kubernetes/guestbook:v2
          ports:
           - containerPort: 80
