---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: guestbook-back

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-back-deployment
spec:
  selector:
    matchLabels:
      app: guestbook-back
  template:
    metadata:
      labels:
        app: guestbook-back
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

