---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-front-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: guestbook-front

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-front-deployment
spec:
  selector:
    matchLabels:
      app: guestbook-front
  template:
    metadata:
      labels:
        app: guestbook-front
    spec:
      containers:
        - name: guestbook-front-container
          image: kubernetes/guestbook:v2
          ports:
            - containerPort: 3000