---

apiVersion: v1
kind: Service
metadata:
  name: jenkins_service
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30002    
  selector:
    app: jenkins

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins:alpine
        ports:
          - containerPort: 8080
#        volumeMounts:
#          - name: jenkins-home
#            mountPath: /var/jenkins_home
#      volumes:
#        - name: jenkins-home
#          # save jenkins data when the container is crash.
#          # for more options review: https://kubernetes.io/docs/concepts/storage/volumes/
#          emptyDir: {}